apiVersion: apps/v1
kind: Deployment
metadata:
  name: goodfood-providers
spec:
  replicas: 1
  selector:
    matchLabels:
      app: goodfood-providers
  template:
    metadata:
      labels:
        app: goodfood-providers
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: goodfood-providers
        image:  beaurval/goodfood-providers:latest
        ports:
        - containerPort: 5001
          name: gf-providers
---
apiVersion: v1
kind: Service
metadata:
  name: goodfood-providers
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5001
  selector:
    app: goodfood-providers