apiVersion: apps/v1
kind: Deployment
metadata:
  name: goodfood-providers
  namespace: {{ default "staging" .Release.Namespace }}
  annotations:
        checksum/config: {{ include (print $.Template.BasePath "/deploy.yaml") . | sha256sum }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: goodfood-providers
  template:
    metadata:
      labels:
        app: goodfood-providers
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: goodfood-providers
        image:  {{ .Values.image.registry }}/{{ .Values.image.name }}:{{ default "latest" .Values.image.tag }}
        ports:
        - containerPort: 5001
          name: gf-providers
