name: Build and push the latest build to staging

on:
  push:
    branches: [ develop ]

jobs:
  build_push_image:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v1

      - name: Docker Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.ACR_LOGIN }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push staging images
        uses: docker/build-push-action@v2
        with:
          context: ./goodfood-providers
          tags: ${{secrets.ACR_NAME}}/goodfood-providers:latest
          push: true
  deploy:
    runs-on: ubuntu-20.04
    needs: build_push_image
    steps:
      - uses: actions/checkout@v2
      - name: Helm tool installer
        uses: Azure/setup-helm@v3.3
        with:
          version: v2.1
      - name: Kubernetes Set Context
        uses: Azure/aks-set-context@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          resource-group: goodfood-pipelines-26697
          cluster-name: goodfood-aks
      - name: Run Helm Deploy
        run: |
          helm upgrade \
          --install \
          --create-namespace \
          --atomic \
          --wait \
          --recreate-pods \
          --namespace staging \
          goodfood-providers \
          ./goodfood-providers/deploy/goodfood-providers \
          --set image.repository=${{secrets.ACR_NAME}}/goodfood-providers:latest \
          --set dns.name=${{ secrets.DNS_NAME }}
