name: Build and push the latest build for products

on:
  push:
    branches: 
      - develop
      - master
    paths: 
      - goodfood-product/**

  pull_request:
    branches:
        - develop
        - master
    paths:
      - goodfood-product/**
jobs:
  build_push_image:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v1

      - name: Docker Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.ACR_LOGIN }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push staging images
        uses: docker/build-push-action@v2
        with:
          context: ./goodfood-product
          tags: ${{secrets.ACR_NAME}}/goodfood-products:latest
          push: true
  deploy:
    runs-on: ubuntu-20.04
    needs: build_push_image
    steps:
      - uses: actions/checkout@v2
      - name: Helm tool installer
        uses: Azure/setup-helm@v3.3
        with:
          version: v3.3.1
      - name: Kubernetes Set Context
        uses: Azure/aks-set-context@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          resource-group: goodfood-pipelines-26697
          cluster-name: goodfood-aks
      - name: Run Helm Deploy
        run: |
          helm upgrade \
          --install \
          --create-namespace \
          --atomic \
          --wait \
          --namespace staging \
          goodfood-product \
          ./goodfood-product/deploy/goodfood-product \
          --set image.repository=${{ secrets.ACR_NAME }} \
          --set dns.name=${{ secrets.DNS_NAME }}
      - name: Re-apply deployments      
        run: kubectl rollout restart deployment goodfood-products -n staging
    
